---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-trust-anchor
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "k8s/linkerd/linkerd-trust-anchor"
