---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  namespace: example
spec:
  provider:
    vault:
      server: "http://vault.vd.ingtra.net:8200"
      path: "kv/k8s"
      version: "v2"
      auth:
        tokenSecretRef:
          namespace: "external-secrets"
          name: "vault-token"
          key: "token"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testme
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "testme"