apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  labels:
    app: litellm
data:
  config.yaml: |
    litellm_settings:
      drop_params: true
    model_list:
      - model_name: google/embeddinggemma-300m
        litellm_params:
          model: hosted_vllm//models/embeddinggemma-300m
          api_base: http://embedding-lb/v1
          api_key: dummy
          max_parallel_requests: 256
      - model_name: google/embeddinggemma-300m-trt
        litellm_params:
          model: triton/embeddinggemma
          api_base: http://triton:8000/v2/models/embeddinggemma/infer
          api_key: dummy
          max_parallel_requests: 256
