apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  labels:
    app: litellm
data:
  config.yaml: |
    litellm_settings:
      drop_params: true
    model_list:
      - model_name: qwen/qwen3-embedding-0.6b
        litellm_params:
          model: hosted_vllm//models/qwen3-embedding-0-6b
          api_base: http://qwen3-embedding-lb/v1
          api_key: dummy
          max_parallel_requests: 256
