apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  ports:
    - port: 8428
      protocol: TCP
      targetPort: 8428
      name: http

---
apiVersion: v1
kind: Endpoints
metadata:
  name: victoria-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.3.65.13
    ports:
      - name: http
        port: 8428
