apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: monitoring
spec:
  ports:
    - port: 8428

---
apiVersion: v1
kind: Endpoints
metadata:
  name: victoria-metrics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.3.65.13
    ports:
      - port: 8428
