apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: istio-ingress-configs
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
