apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v24.9.1
    helm:
      releaseName: gpu-operator
      values: |
        operator:
          defaultRuntime: containerd
        devicePlugin:
          env:
            - name: PASS_DEVICE_SPECS
              value: "true"
            - name: FAIL_ON_INIT_ERROR
              value: "false"
            - name: DEVICE_LIST_STRATEGY
              value: envvar
            - name: DEVICE_ID_STRATEGY
              value: uuid
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
        toolkit:
          env:
            - name: CONTAINERD_CONFIG
              value: /etc/k0s/containerd.d/gpuoperator.toml
            - name: CONTAINERD_SOCKET
              value: /run/k0s/containerd.sock
            - name: CONTAINERD_RUNTIME_CLASS
              value: nvidia
  destination:
    server: https://kubernetes.default.svc
    namespace: gpu-operator
