apiVersion: v1
kind: Namespace
metadata:
  name: lakekeeper

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakekeeper  
  namespace: argocd
spec:
  project: default
  source:
    chart: lakekeeper
    repoURL: https://lakekeeper.github.io/lakekeeper-charts
    targetRevision: 0.2.1
    helm:
      releaseName: lakekeeper
      values: |
        externalDatabase:
          database: lakekeeper
          host_read: postgresql.vd.ingtra.net
          host_write: postgresql.vd.ingtra.net
          user: system
          password: systemsecret
        postgresql:
          enabled: false
        catalog:
          config:
            ICEBERG_REST__BASE_URL: https://lakekeeper.ig.ingtra.net
  destination:
    server: https://kubernetes.default.svc
    namespace: lakekeeper
