apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-core-v2-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: seldon-core-v2-crds
    repoURL: https://seldonio.github.io/helm-charts
    targetRevision: 2.7.0
    helm:
      releaseName: seldon-core-v2-crds
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - Replace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-core-v2
  namespace: argocd
spec:
  project: default
  source:
    chart: seldon-core-v2-setup
    repoURL: https://seldonio.github.io/helm-charts
    targetRevision: 2.7.0
    helm:
      releaseName: seldon-core-v2
      values: |
        opentelemetry:
          disable: true
        kafka:
          bootstrap: redpanda.sd.ingtra.net:9092
          topicPrefix: svc.seldon.
          consumerGroupIdPrefix: svc.seldon.
        services:
          serviceGRPCPrefix: "grpc-"
          defaultServiceType: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: seldon-mesh

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: seldon-configs
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: seldon-mesh