apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
spec:
  type: Scala
  mode: cluster
  image: harbor.ingtra.net/library/spark:3.2.1
  imagePullPolicy: Always
  mainClass: net.ingtra.sparking.loader.LoaderApp
  mainApplicationFile: http://minio.mdc.ingtra.net/bins/sparking/jars/sparking-assembly-0.1.0-SNAPSHOT.jar
  arguments:
    - http://minio.mdc.ingtra.net/bins/sparking/configs/twitter/streaming_sampled_tweets.yaml
  sparkVersion: 3.2.1
  restartPolicy:
    type: OnFailure
  driver:
    cores: 1
    coreRequest: 100m
    memory: "512m"
    labels:
      version: 3.2.1
  executor:
    cores: 1
    coreRequest: 100m
    instances: 1
    memory: "512m"
    labels:
      version: 3.2.1