apiVersion: v1
kind: Service
metadata:
  name: nitro-e
  labels:
    app: nitro-e-dist
spec:
  selector:
    app: nitro-e-dist
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
