apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-filebeat
  namespace: argocd
spec:
  project: default
  source:
    chart: filebeat
    repoURL: https://airflow.apache.org
    targetRevision: 7.17.1
    helm:
      releaseName: airflow-filebeat
      values: |
        daemonset:
          filebeatConfig:
            filebeat.yml: |
              logging.json: true
              filebeat.config:
                inputs:
                  # Mounted `filebeat-inputs` configmap:
                  path: ${path.config}/inputs.d/*.yml
                  # Reload inputs configs as they change:
                  reload.enabled: false
                modules:
                  path: ${path.config}/modules.d/*.yml
                  # Reload module configs as they change:
                  reload.enabled: false
              filebeat.autodiscover:
                providers:
                  - type: kubernetes
                    templates:
                    - condition:
                        equals:
                          kubernetes.namespace: airflow
                      config:
                        - type: container
                          paths:
                          - /var/log/containers/*${data.kubernetes.container.id}.log
                          multiline.pattern: '^[[:space:]]'
                          multiline.negate: false
                          multiline.match: after
                          include_lines: ['^{']
              processors:
                - decode_json_fields:
                    fields: ["message"]
                    max_depth: 1
                    target: ""
                    overwrite_keys: true
                    add_error_key: true
              output.elasticsearch:
                hosts: ["http://elasticsearch.mdc.ingtra.net:9200"] 
                index: "airflow-dags-%{+yyyy.MM.dd}"
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
