apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: 1.5.0
    helm:
      releaseName: airflow
      values: |
        defaultAirflowRepository: harbor.ingtra.net/dockerhub/apache/airflow
        executor: "KubernetesExecutor"
        dags:
          gitSync:
            enabled: true
            repo: https://github.com/ingtranet/airflow-dags.git
            branch: master
            rev: HEAD
            depth: 1
            subPath: dags
            wait: 300
        data:
          metadataConnection:
            user: airflow
            pass: airflow
            protocol: mysql
            host: mysql.mdc.ingtra.net
            port: 3306
            db: airflow
            sslmode: disable
        createUserJob:
          useHelmHooks: false
        migrateDatabaseJob:
          useHelmHooks: false
        postgresql:
          enabled: false
        statsd:
          enabled: true
        webserver:
          webserverConfig: |
            AUTH_ROLE_PUBLIC = 'Admin'
        elasticsearch:
          enabled: true
          connection:
            host: elasticsearch.mdc.ingtra.net
            port: 9200
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
