---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coder/code-server
    path: ci/helm-chart
    targetRevision: HEAD
    helm:
      releaseName: code-server
      values: |
        persistence:
          enabled: false
        nodeSelector:
          kubernetes.io/hostname: k8s-ga-gpu-1
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
