
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: default
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.2
    helm:
      releaseName: istio-base
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.2
    helm:
      releaseName: istiod
      values: |
        pilot:
          autoscaleEnabled: false
        meshConfig:
          trustDomain: kg.ingtra.net
        global:
          proxy:
            clusterDomain: kg.ingtra.net
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress-gateway
  namespace: argocd
spec:
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.20.2
    helm:
      releaseName: istio-internal-ingress
      values: |
        autoscaling:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
