apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kestra
  namespace: argocd
spec:
  project: default
  source:
    chart: kestra
    repoURL: https://helm.kestra.io
    targetRevision: 0.5.1
    helm:
      releaseName: kestra
      values: |
        image:
          image: harbor.ingtra.net/dockerhub/kestra/kestra
          tag: v0.6.0-full
        minio:
          enabled: false
        postgresql:
          enabled: false
        configuration: |
          kestra:
            queue:
              type: mysql
            repository:
              type: mysql
            storage:
              type: minio
              minio:
                endpoint: s3.seaweedfs.mdc.ingtra.net
                port: 80
                accessKey: kestra
                secretKey: kestrasecret
                bucket: kestra
            datasources:
              mysql:
                url: jdbc:mysql://mysql.mdc.ingtra.net:3306/kestra
                driverClassName: com.mysql.cj.jdbc.Driver
                username: kestra
                password: kestra
                dialect: MYSQL
  destination:
    server: https://kubernetes.default.svc
    namespace: kestra
