apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    chart: kibana
    repoURL: https://helm.elastic.co
    targetRevision: 7.17.1
    helm:
      releaseName: kibana
      values: |
        elasticsearchHosts: http://elasticsearch.mdc.ingtra.net:9200
        extraEnvs:
          - name: "NODE_OPTIONS"
            value: "--max-old-space-size=1800"
  destination:
    server: https://kubernetes.default.svc
    namespace: kibana