apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts.git
    targetRevision: main
    path: kibana
    helm:
      releaseName: kibana
      values: |
        elasticsearchHosts:
          - http://elasticsearch.mdc.ingtra.net:9200
      resources: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: kibana