apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    chart: kibana
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      releaseName: kibana
      values: |
        elasticsearchHosts: http://elasticsearch.mdc.ingtra.net:9200
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: kibana