apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyuubi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/helm-charts.git
    path: kyuubi
    targetRevision: main
    helm:
      releaseName: kyuubi
      values: |
        replicaCount: 1
        image:
          repository: harbor.ingtra.net/library/kyuubi
          tag: 1.5.1-s3.2.1
        service:
          type: LoadBalancer
        additionalConfigProperties:
         - spark.driver.extraJavaOptions=-XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact
         - spark.driver.memory=1G
         - spark.executor.extraJavaOptions=-XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact
         - spark.executor.memory=1G
         - spark.executor.memoryOverhead=1G
         - spark.shuffle.io.preferDirectBufs=false
         - spark.network.io.preferDirectBufs=false
         - spark.eventLog.gcMetrics.youngGenerationGarbageCollectors="Shenandoah Cycles"
         - spark.eventLog.gcMetrics.oldGenerationGarbageCollectors="Shenandoah Pauses"
         - spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
         - spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog
         - spark.sql.catalog.iceberg.type=hive
         - spark.sql.catalog.iceberg.uri=thrift://hive-metastore.mdc.ingtra.net:9083
         - spark.sql.catalog.iceberg.hadoop.fs.s3a.endpoint=http://minio.mdc.ingtra.net
         - spark.sql.catalog.iceberg.warehouse=s3a://iceberg/
         - spark.sql.catalog.iceberg.hive.metastore.warehouse.dir=s3a://iceberg/
         - spark.hadoop.fs.s3a.access.key=spark
         - spark.hadoop.fs.s3a.secret.key=sparkuser
         - spark.hadoop.fs.s3a.connection.ssl.enabled=false
         - spark.hadoop.fs.s3a.fast.upload=true
         - spark.hadoop.fs.s3a.bucket.all.committer.magic.enabled=true
         - spark.kubernetes.namespace=airflow
         - spark.kubernetes.authenticate.driver.serviceAccountName=spark
         - spark.kubernetes.container.image=harbor.ingtra.net/library/spark:3.2.1
         - spark.kubernetes.container.image.pullPolicy=Always
         - spark.kubernetes.executor.podTemplateFile=http://minio.mdc.ingtra.net/bins/spark/executor_pod_template.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kyuubi