---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-bootstrap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: linkerd-bootstrap
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.8.0
    helm:
      releaseName: linkerd-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.16.9
    helm:
      releaseName: linkerd-control-plane
      values: |
        clusterDomain: kg.ingtra.net
        controllerImage: ghcr.io/linkerd/controller
        debugContainer:
          image:
            name: ghcr.io/linkerd/debug
        policyController:
          image:
            name: ghcr.io/linkerd/policy-controller
        proxy:
          image:
            name: ghcr.io/linkerd/proxy
        proxyInit:
          image:
            name: ghcr.io/linkerd/proxy-init
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIBjTCCATOgAwIBAgIQOXelNBvtv5D3m5OlV+ySvzAKBggqhkjOPQQDAjAlMSMw
          IQYDVQQDExpyb290LmxpbmtlcmQua2cuaW5ndHJhLm5ldDAeFw0yNDAxMTUxNTI4
          MTVaFw0zNDAxMTIxNTI4MTVaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5rZy5p
          bmd0cmEubmV0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEMnSiVVO1fKmX4Eao
          n7HuUYZ3Yn9ZLA/u2wiBv5i/8Dd6dujFDB3mTDzKC28+uepJDTLny828bVnSEWn6
          9nJRM6NFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
          VR0OBBYEFOcAXqadcY/KQzCe9MFgAiypvWZ/MAoGCCqGSM49BAMCA0gAMEUCIQDB
          u4OGl3EL+E0j5kvywdAcHG/ZUkQKOzZptCX5YQKc8QIgXk7nq1Uhzw2VjF71OVDy
          iXTAPutNqf6lWlNZVcuOEaU=
          -----END CERTIFICATE-----
        identity:
          issuer:
            scheme: kubernetes.io/tls
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  ignoreDifferences:
    - group: ""
      kind: Secret
      name:  linkerd-proxy-injector-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: ""
      kind: Secret
      name:  linkerd-sp-validator-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: ""
      kind: Secret
      name:  linkerd-policy-validator-k8s-tls
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
    - group: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name:  linkerd-proxy-injector-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name:  linkerd-sp-validator-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name:  linkerd-policy-validator-webhook-config
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
spec:
  project: default
  source:
    chart: linkerd-viz
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 30.12.9
    helm:
      releaseName: linkerd-viz
      values: |
        defaultRegistry: ghcr.io/linkerd
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd