apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    chart: nvidia-device-plugin
    repoURL: https://nvidia.github.io/k8s-device-plugin
    targetRevision: 0.14.3
    helm:
      releaseName: nvidia-device-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin
