apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-core-v2-crds
  namespace: argocd
spec:
  project: default
  source:
    chart: seldon-core-v2-crds
    repoURL: https://seldonio.github.io/helm-charts
    targetRevision: 2.7.0
    helm:
      releaseName: seldon-core-v2-crds
  destination:
    server: https://kubernetes.default.svc

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-core-v2
  namespace: argocd
spec:
  project: default
  source:
    chart: seldon-core-v2
    repoURL: https://seldonio.github.io/helm-charts
    targetRevision: 2.7.0
    helm:
      releaseName: seldon-core-v2
      values: |
        controller:
          clusterwide: true
  destination:
    server: https://kubernetes.default.svc
    namespace: seldon-mesh

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-v2-runtime
  namespace: argocd
spec:
  project: default
  source:
    chart: seldon-v2-runtime
    repoURL: https://seldonio.github.io/helm-charts
    targetRevision: 2.7.0
    helm:
      releaseName: seldon-v2-runtime
  destination:
    server: https://kubernetes.default.svc
    namespace: seldon-mesh

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seldon-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: seldon-configs
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: seldon-mesh