apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.14.2
    helm:
      releaseName: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik