apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: argocd
spec:
  project: default
  source:
    chart: trino
    repoURL: https://trinodb.github.io/charts
    targetRevision: 0.7.0
    #repoURL: https://github.com/trinodb/charts.git
    #path: charts/trino
    #targetRevision: main
    helm:
      releaseName: trino
      values: |
        image:
          repository: harbor.ingtra.net/dockerhub/trinodb/trino
          tag: "377"
        server:
          workers: 6
          coordinatorExtraConfig: |
            web-ui.user=admin
            web-ui.authentication.type=fixed
          config:
            query:
              maxMemory: 4GB
              maxMemoryPerNode: 512MB
            memory:
              heapHeadroomPerNode: 256MB
          exchangeManager:
            name: "filesystem"
            baseDir: "s3a://trino/exchange"
        coordinator:
          jvm:
            maxHeapSize: 1G
        worker:
          jvm:
            maxHeapSize: 1G
          resources:
            requests:
              cpu: 0.1
            limits:
              cpu: 1
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: component
                        operator: In
                        values: ["worker"]
                  topologyKey: "kubernetes.io/hostname"
        additionalCatalogs:
          iceberg: |
            connector.name=iceberg
            hive.metastore.uri=thrift://hive-metastore.mdc.ingtra.net:9083
            hive.s3.aws-access-key=trino
            hive.s3.aws-secret-key=trinouser
            hive.s3.endpoint=http://minio.mdc.ingtra.net
            hive.s3.ssl.enabled=false
            hive.s3.path-style-access=true
        additionalConfigProperties:
          - spill-enabled=true
          - spiller-spill-path=/tmp
          - spill-compression-enabled=true
          - query-max-spill-per-node=10GB
          - retry-policy=TASK
          - enable-dynamic-filtering=false
        additionalExchangeManagerProperties:
          - exchange.encryption-enabled=false
          - exchange.s3.aws-access-key=trino
          - exchange.s3.aws-secret-key=trinouser
          - exchange.s3.endpoint=http://minio.mdc.ingtra.net
          - exchange.s3.region=us-east-1

  destination:
    server: https://kubernetes.default.svc
    namespace: trino