apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: vault-secrets-operator
    repoURL: https://ricoberger.github.io/helm-charts
    targetRevision: 1.16.5
    helm:
      releaseName: vault-secrets-operator
      values: |
        vault:
          address: http://vault.vd.ingtra.net:8200
        environmentVars:
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault-secrets-operator
                key: VAULT_TOKEN
          - name: VAULT_TOKEN_LEASE_DURATION
            valueFrom:
              secretKeyRef:
                name: vault-secrets-operator
                key: VAULT_TOKEN_LEASE_DURATION
          - name: VAULT_TOKEN_RENEWAL_INTERVAL
            valueFrom:
              secretKeyRef:
                name: vault-secrets-operator
                key: VAULT_TOKEN_RENEWAL_INTERVAL
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-secrets-operator
