apiVersion: apps/v1
kind: Deployment
metadata:
  name: motorcoach
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: motorcoach
  template:
    metadata:
      labels:
        app.kubernetes.io/name: motorcoach
    spec:
      containers:
        - name: motorcoach
          image: harbor.ingtra.net/library/motorcoach:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: "1"
              memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: motorcoach
spec:
  selector:
    app.kubernetes.io/name: motorcoach
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
