---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ig-ingtra-net
spec:
  secretName: ig-ingtra-net-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - '*.ig.ingtra.net'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingtra-net
spec:
  secretName: ingtra-net-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - '*.ingtra.net'