apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    chart: actions-runner-controller 
    targetRevision: 0.23.7
    helm:
      releaseName: actions-runner-controller        
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: manifests/actions-runner-configs
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner