apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://airflow.apache.org
    chart: airflow 
    targetRevision: 1.18.0
    helm:
      releaseName: airflow
      valuesObject:
        image:
          airflow:
            tag: 3.1.5-python3.13
        executor: "KubernetesExecutor"
        allowPodLaunching: true
        allowJobLaunching: true
        data:
          metadataSecretName: "secrets"
        triggerer:
          persistence:
            enabled: false
        fernetKeySecretName: "secrets"
        apiSecretKeySecretName: "secrets"
        migrateDatabaseJob:
          useHelmHooks: false
        jwtSecretName: "secrets"
        postgresql:
          enabled: false
        config:
          core:
            simple_auth_manager_all_admins: "True"
            xcom_backend: "airflow.providers.common.io.xcom.backend.XComObjectStorageBackend"
          "common.io":
              xcom_objectstorage_path: "s3://ingtranet_s3@airflow/xcoms"
              xcom_objectstorage_threshold: 0
              xcom_objectstorage_compression: "gzip"
          logging:
            remote_logging: "True"
            remote_base_log_folder: "s3://airflow/logs"
            remote_log_conn_id: "ingtranet_s3"
            encrypt_s3_logs: "False"
          dag_processor:
            dag_bundle_config_list: '[{"name": "example_bundles", "classpath": "airflow.providers.git.bundles.git.GitDagBundle", "kwargs": {"tracking_ref": "main", "git_conn_id": "common_airflow_dags"}}]'  
          
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
