apiVersion: v1
kind: Namespace
metadata:
  name: amoro

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amoro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/apache/amoro.git
    path: charts/amoro
    targetRevision: 2f8d9d0
    helm:
      releaseName: amoro
      values: |
        clusterDomain: kd.ingtra.net
        image:
          tag: "0.8.1-incubating"
        jvmOptions: |
          xms=3072
          xmx=3072
          gc=UseShenandoahGC
        amoroConf:
          amoroDefaults: |
            ams:
              server-bind-host: "0.0.0.0"
              server-expose-host: "127.0.0.1"
              http-server:
                bind-port: 1630
              self-optimizing:
                enabled: true
              expire-snapshots:
                enabled: true
              clean-orphan-files:
                enabled: true
                interval: 1d
              clean-dangling-delete-files:
                enabled: true
              data-expiration:
                enabled: true
                interval: 1d
              database:
                type: postgres
                jdbc-driver-class: org.postgresql.Driver
                url: jdbc:postgresql://postgresql.vd.ingtra.net:5432/amoro
                username: system
                password: systemsecret
        optimizer:
          local:
            enabled: false
          kubernetes:
            enabled: false # it needs kubeconfig file
          flink:
            properties:
              "flink-conf.taskmanager.memory.managed.size": "32mb"
              "flink-conf.taskmanager.memory.network.max": "32mb"
              "flink-conf.taskmanager.memory.network.min": "32mb"
              "flink-conf.kubernetes.namespace": "amoro"
              "flink-conf.kubernetes.service-account": "amoro"
          spark:
            properties:
              "master": "k8s://https://kubernetes.default.svc"
              "deploy-mode": "cluster"
              "spark-conf.spark.dynamicAllocation.enabled": "true"
              "spark-conf.spark.shuffle.service.enabled": "false"
              "spark-conf.spark.dynamicAllocation.shuffleTracking.enabled": "true"
              "spark-conf.spark.kubernetes.namespace": "amoro"
              "spark-conf.spark.kubernetes.authenticate.driver.serviceAccountName": "amoro"
        resources:
          limits:
            memory: 4Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: amoro
