apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.15.3
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        startupapicheck:
          podAnnotations:
            sidecar.istio.io/inject: "false"
        extraArgs:
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: manifests/cert-manager-configs
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
