apiVersion: v1
kind: Namespace
metadata:
  name: coder

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
spec:
  project: default
  source:
    chart: coder
    repoURL: https://helm.coder.com/v2
    targetRevision: 2.23.1
    helm:
      releaseName: coder
      values: |
        coder:
          env:
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: coder-db-url
            - name: CODER_ACCESS_URL
              value: "https://coder.ig.ingtra.net"
            - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
              value: "false"
            - name: CODER_OIDC_ISSUER_URL
              value: "http://10.1.0.12:9000/application/o/coder/"
            - name: CODER_OIDC_EMAIL_DOMAIN
              value: "gmail.com"
            - name: CODER_OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: coder-oidc-client-id
            - name: CODER_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: coder-oidc-client-secret
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: coder
