apiVersion: v1
kind: Namespace
metadata:
  name: immich

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/immich-app/immich-charts
    chart: immich
    targetRevision: 0.9.3
    helm:
      releaseName: immich
      values: |
        env:
          TZ: "Asia/Seoul"
          NO_COLOR: "true"
          DB_URL: postgresql://system:systemsecret@vchord.vd.ingtra.net:5432/immich
          DB_VECTOR_EXTENSION: vectorchord
          REDIS_HOSTNAME: kvrocks.vd.ingtra.net
          REDIS_PORT: "6379"
          REDIS_PASSWORD: immich
        image:
          tag: v1.135.3
        immich:
          persistence:
            library:
              existingClaim: nfs-immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
