apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.3.4
    helm:
      releaseName: grafana
      values: |
        assertNoLeakedSecrets: false
        grafana.ini:
          analytics:
            reporting_enabled: false
            check_for_plugin_updates: true
          auth:
            disable_login: true
            disable_login_form: true
            disable_signout_menu: true
          auth.anonymous:
            enabled: true
            org_name: Main Org.
            org_role: Admin
          auth.basic:
            enabled: false
          server:
            domain: grafana.ig.ingtra.net
            root_url: "%(protocol)s://%(domain)s"
          database:
            type: postgres
            host: postgresql.vd.ingtra.net:5432
            name: grafana
            user: system
            password: systemsecret
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.23.3
    helm:
      releaseName: tempo
      values: |
        replicas: 2
        tempo:
          reportingEnabled: false
          storage:
            trace:
              backend: s3
              s3:
                bucket: tempo
                prefix: trace/
                endpoint: s3.ingtra.net
                access_key: system
                secret_key: systemsecret
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    chart: alloy
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.2.1
    helm:
      releaseName: alloy
      values: |
        alloy:
          clustering:
            enabled: true
          configMap:
            content: |
              otelcol.receiver.otlp "default" {
                http {
                  endpoint = "127.0.0.1:4318"
                }
                output {
                  traces  = [otelcol.processor.batch.default.input]
                }
              }
              otelcol.processor.batch "default" {
                output {
                  traces  = [otelcol.exporter.otlphttp.default.input]
                }
              }
              otelcol.exporter.otlphttp "default" {
                client {
                  endpoint = "tempo.monitoring.svc:4318"
                }
              }
          extraPorts:
            - name: "otel-http"
              port: 4318
              targetPort: 4318
              protocol: "TCP"
              appProtocol: "http"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring