apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.3.4
    helm:
      releaseName: grafana
      values: |
        assertNoLeakedSecrets: false
        grafana.ini:
          analytics:
            reporting_enabled: false
            check_for_plugin_updates: true
          auth:
            disable_login: true
            disable_login_form: true
            disable_signout_menu: true
          auth.anonymous:
            enabled: true
            org_name: Main Org.
            org_role: Admin
          auth.basic:
            enabled: false
          server:
            domain: grafana.ig.ingtra.net
            root_url: "%(protocol)s://%(domain)s"
          database:
            type: postgres
            host: postgresql.vd.ingtra.net:5432
            name: grafana
            user: system
            password: systemsecret
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.23.3
    helm:
      releaseName: tempo
      values: |
        replicas: 1
        tempo:
          reportingEnabled: false
          ingester:
            max_block_duration: 5m
            flush_all_on_shutdown: true
          metricsGenerator:
            enabled: true
          storage:
            trace:
              backend: s3
              s3:
                bucket: tempo
                prefix: trace/
                endpoint: s3.ingtra.net
                access_key: system
                secret_key: systemsecret
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    chart: alloy
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.2.1
    helm:
      releaseName: alloy
      values: |
        alloy:
          clustering:
            enabled: true
          configMap:
            content: |
              otelcol.receiver.otlp "default" {
                http {
                  endpoint = "0.0.0.0:4318"
                }
                output {
                  metrics = [otelcol.processor.batch.default.input]
                  logs    = [otelcol.processor.batch.default.input]
                  traces  = [otelcol.processor.batch.default.input]
                }
              }
              otelcol.processor.batch "default" {
                output {
                  metrics = [otelcol.exporter.otlp.signoz.input]
                  logs = [otelcol.exporter.otlp.signoz.input]
                  traces = [
                    otelcol.exporter.otlp.signoz.input,
                    otelcol.exporter.otlp.default.input,
                  ]
                }
              }
              otelcol.exporter.otlp "default" {
                client {
                  endpoint = "tempo.monitoring.svc:4317"
                  tls {
                      insecure             = true
                      insecure_skip_verify = true
                  }
                }
              }
              otelcol.exporter.otlp "signoz" {
                client {
                  endpoint = "signoz.vd.ingtra.net:4317"
                  tls {
                      insecure             = true
                      insecure_skip_verify = true
                  }
                }
              }
          extraPorts:
            - name: "otel-http"
              port: 4318
              targetPort: 4318
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.37.0
    helm:
      releaseName: loki
      values: |
        global:
          clusterDomain: kd.ingtra.net
          dnsService: rke2-coredns-rke2-coredns
        loki:
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            bucketNames:
              chunks: loki-chunk
              ruler: loki-ruler
              admin: loki-admin
            type: s3
            s3:
              endpoint: s3.ingtra.net
              accessKeyId: system
              secretAccessKey: systemsecret
          ingester:
            chunk_encoding: snappy
          tracing:
            enabled: true
          querier:
            max_concurrent: 4

        deploymentMode: SimpleScalable

        backend:
          replicas: 1
        read:
          replicas: 1
        write:
          replicas: 1
        singleBinary:
          replicas: 0
        ingester:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        queryScheduler:
          replicas: 0
        distributor:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        bloomCompactor:
          replicas: 0
        bloomGateway:
          replicas: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring