apiVersion: v1
kind: Namespace
metadata:
  name: nats

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 2.12.6
    helm:
      releaseName: nats
      values: |
        config:
          jetstream:
            enabled: true
            fileStore:
              enabled: false
            memoryStore:
              enabled: true
              maxSize: 1Gi
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: nats
