apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-device-plugin

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-device-plugin
  namespace: argocd
spec:
  project: default
  source:
    chart: nvidia-device-plugin
    repoURL: https://nvidia.github.io/k8s-device-plugin
    targetRevision: 0.17.0
    helm:
      releaseName: nvidia-device-plugin
      values: |
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-da-gpu-2
                      - orin-nx-1
                      - orin-nx-2
                      - orin-nx-3
        tolerations:
          - key: ingtra.net/gpu
            operator: Equal
            value: "true"
            effect: NoSchedule
        gfd:
          enabled: true
        nfd:
          worker:
            tolerations:
              - key: ingtra.net/gpu
                operator: Equal
                value: "true"
                effect: NoSchedule
        runtimeClassName: nvidia
  destination:
    server: https://kubernetes.default.svc
    namespace: nvidia-device-plugin