apiVersion: v1
kind: Namespace
metadata:
  name: prefect

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prefect
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prefecthq.github.io/prefect-helm
    chart: prefect-server
    targetRevision: 2026.9.14141910
    helm:
      releaseName: prefect
      valuesObject:
        server:
          automountServiceAccountToken: false
          uiConfig:
            prefectUiApiUrl: https://prefect.ig.ingtra.net/api
        ingress:
          enabled: false
        externalDatabase:
          existingSecret: prefect-database
          connectionStringSecretKey: connection-string
          host: postgresql.vd.ingtra.net
          port: 5432
          name: prefect
          username: system
        secret:
          create: false
          name: prefect-database
        postgresql:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: prefect

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prefect-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: manifests/prefect
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prefect
