apiVersion: v1
kind: Namespace
metadata:
  name: clearml

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml
  namespace: argocd
spec:
  project: default
  source:
    chart: clearml
    repoURL:  https://allegroai.github.io/clearml-helm-charts
    targetRevision: 7.11.3
    helm:
      releaseName: clearml
      values: |
        clearml:
          cookieDomain: clearml.ig.ingtra.net
        apiserver:
          service:
            type: ClusterIP
          ingress:
            enabled: false
          extraEnvs:
            - name: CLEARML_REDIS_SERVICE_PASSWORD
              value: clearmlsecret
        fileserver:
          service:
            type: ClusterIP
          ingress:
            enabled: false
          extraEnvs:
            - name: CLEARML_REDIS_SERVICE_PASSWORD
              value: clearmlsecret
        webserver:
          service:
            type: ClusterIP
          ingress:
            enabled: false
        redis:
          enabled: false
        mongodb:
          enabled: false
        elasticsearch:
          enabled: false
        externalServices:
          elasticsearchConnectionString: |
            [{"scheme": "http", "host": "elasticsearch.vd.ingtra.net", "port":9200}]
          mongodbConnectionStringAuth: mongodb://mongodb.vd.ingtra.net:27017/clearml_auth
          mongodbConnectionStringBackend: mongodb://mongodb.vd.ingtra.net:27017/clearml_backend
          redisHost: kvrocks.vd.ingtra.net
          redisPort: 6666
  destination:
    server: https://kubernetes.default.svc
    namespace: clearml
