apiVersion: v1
kind: Namespace
metadata:
  name: fission-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: fission

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fission-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fission/fission.git
    path: crds/v1
    targetRevision: v1.20.5
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: fission-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fission
  namespace: argocd
spec:
  project: default
  source:
    chart: fission-all
    repoURL: https://fission.github.io/fission-charts
    targetRevision: v1.20.5
    helm:
      releaseName: fission
      values: |
        routerServiceType: ClusterIP
        defaultNamespace: fission
  destination:
    server: https://kubernetes.default.svc
    namespace: fission-system
