apiVersion: v1
kind: Namespace
metadata:
  name: jupyter

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter
  namespace: argocd
spec:
  project: default
  source:
    chart: jupyterhub
    repoURL: https://hub.jupyter.org/helm-chart
    targetRevision: 3.3.8
    helm:
      releaseName: jupyterhub
      values: |
        hub:
          db:
            type: postgres
            url: postgresql+psycopg2://system:systemsecret@postgresql.vd.ingtra.net:5432/jupyterhub
        proxy:
          service:
            type: ClusterIP
        prePuller:
          hook:
            enabled: false
          continuous:
            enabled: false
        singleuser:
          # Defines the default image
          image:
            name: quay.io/jupyter/base-notebook
            tag: "2024-09-16"
          networkPolicy:
            enabled: false
          allowPrivilegeEscalation: true
          extraEnv:
            GRANT_SUDO: "yes"
            CLEARML_WEB_HOST: https://app.clearml.ig.ingtra.net
            CLEARML_API_HOST: https://api.clearml.ig.ingtra.net
            CLEARML_FILES_HOST: https://files.clearml.ig.ingtra.net
            CLEARML_API_ACCESS_KEY: 3J5SAEPD5RCL11EGWOIQ5XP85XCAQ7
            CLEARML_API_SECRET_KEY: DdbtoHKh7k0SQq5nUtFwoGvAt_TRmW351ZVtRn2QH_PsgSNTXlXK1LDz5byoRf-PScU
            CLEARML_LOG_MODEL: "FALSE"
          profileList:
            - display_name: "Default environment"
              description: "The default image."
              default: true
            - display_name: "GPU environment"
              description: "The image with GPU support."
              kubespawner_override:
                image: quay.io/jupyter/pytorch-notebook:cuda12-2024-09-16
                node_selector:
                  nvidia.com/gpu.product: NVIDIA-GeForce-RTX-3090


  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
