apiVersion: v1
kind: Namespace
metadata:
  name: kubero

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubero
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubero-dev/kubero-operator.git
      targetRevision: v0.1.5
      path: deploy/operator.0.1.5.yaml
    - repoURL: https://github.com/ingtranet/argocd-manifests.git
      path: manifests/kubero-configs
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
