apiVersion: v1
kind: Namespace
metadata:
  name: nessie

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessie
  namespace: argocd
spec:
  project: default
  source:
    chart: nessie
    repoURL: https://charts.projectnessie.org
    targetRevision: 0.95.0
    helm:
      releaseName: nessie
      values: |
        versionStoreType: JDBC
        jdbc:
          jdbcUrl: jdbc:postgresql://postgresql.vd.ingtra.net:5432/nessie
          secret:
            name: nessie-db
            username: username
            password: password
        advancedConfig:
          nessie.catalog.warehouseDefaults.default-warehouse: s3://iceberg
          nessie.catalog.service.s3.default-options.region=us-west-2
          nessie.catalog.service.s3.default-options.access-key.name=system
          nessie.catalog.service.s3.default-options.access-key.secret=systemsecret
          nessie.catalog.service.s3.default-options.endpoint=https://s3.sf.ingtra.net

          
  destination:
    server: https://kubernetes.default.svc
    namespace: nessie
