apiVersion: v1
kind: Namespace
metadata:
  name: nessie

# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: nessie-gc-job
#   namespace: nessie
# spec:
#   template:
#     spec:
#       containers:
#         - name: nessie-gc
#           image: ghcr.io/projectnessie/nessie-gc
#           args: 
#             - gc
#             - --uri
#             - https://nessie.ig.ingtra.net/api/v2
#             - --jdbc
#             - --jdbc-url
#             - "jdbc:postgresql://postgresql.vd.ingtra.net:5432/nessie_gc"
#             - --jdbc-user
#             - "$(JDBC_USER)"
#             - --jdbc-password
#             - "$(JDBC_PASSWORD)"
#             - --iceberg
#             - s3.access-key-id=system,s3.secret-access-key=systemsecret,s3.endpoint=https://s3.sf.ingtra.net
#           env:
#             - name: JDBC_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: nessie-db
#                   key: username
#             - name: JDBC_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: nessie-db
#                   key: password
#             - name: AWS_REGION
#               value: us-west-2
#           resources:
#             limits:
#               memory: "2Gi"
#               cpu: "1"
#       restartPolicy: Never

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessie
  namespace: argocd
spec:
  project: default
  source:
    chart: nessie
    repoURL: https://charts.projectnessie.org
    targetRevision: 0.101.3
    helm:
      releaseName: nessie
      values: |
        versionStoreType: JDBC
        jdbc:
          jdbcUrl: jdbc:postgresql://postgresql.vd.ingtra.net:5432/nessie
          secret:
            name: nessie-db
            username: username
            password: password
        catalog:
          storage:
            s3:
              defaultOptions:
                accessKeySecret:
                  awsAccessKeyId: system
                  accessKeySecret: systemsecret
                endpoint: https://s3.sf.ingtra.net
                region: us-west-1
          iceberg:
            defaultWarehouse: iceberg
            warehouses:
              - name: iceberg
                location: s3://iceberg
  destination:
    server: https://kubernetes.default.svc
    namespace: nessie
