apiVersion: v1
kind: Namespace
metadata:
  name: nessie

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nessie
  namespace: argocd
spec:
  project: default
  source:
    chart: nessie
    repoURL: https://charts.projectnessie.org
    targetRevision: 0.95.0
    helm:
      releaseName: nessie
      values: |
        versionStoreType: JDBC
        jdbc:
          jdbcUrl: jdbc:postgresql://postgresql.vd.ingtra.net:5432/nessie
          secret:
            name: nessie-db
            username: username
            password: password
        catalog:
          enabled: true
          iceberg:
            defaultWarehouse: s3://iceberg
          # storage:
          #   s3:
          #     defaultOptions:
          #       endpoint: https://s3.sf.ingtra.net

          
  destination:
    server: https://kubernetes.default.svc
    namespace: nessie
