apiVersion: v1
kind: Namespace
metadata:
  name: omniamni

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omniamni
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: manifests/omniamni
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: omniamni
