apiVersion: v1
kind: Namespace
metadata:
  name: traefik

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 30.0.0
    helm:
      releaseName: traefik
      values: |
        deployment:
          replicas: 2
        nodeSelector:
          k8s.ingtra.net/persistent: "true"
        topologySpreadConstraints:
          - labelSelector:
              matchLabels:
                app: '{{ template "traefik.name" . }}'
            maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
            allowExternalNameServices: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ingtranet/argocd-manifests.git
    path: manifests/traefik-configs
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
