apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver
spec:
  replicas: 1
  serverConfig: mlserver

---
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: triton
spec:
  replicas: 1
  serverConfig: triton