apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ig-ingtra-net-tls
spec:
  secretName: ig-ingtra-net-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - '*.ig.ingtra.net'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ks-ingtra-net-tls
spec:
  secretName: ks-ingtra-net-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - '*.ks.ingtra.net'
