apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clearml
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`clearml.ig.ingtra.net`)
      services:
        - kind: Service
          name: clearml-webserver
          namespace: clearml
          port: 80
  tls:
    secretName: ig-ingtra-net-tls
