apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: localai
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`localai.ig.ingtra.net`)
      services:
        - kind: Service
          name: localai
          namespace: llm-serving
          port: 80
  tls:
    secretName: ig-ingtra-net-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: localai-sticky
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`localai-st.ig.ingtra.net`)
      services:
        - kind: Service
          name: localai
          namespace: llm-serving
          port: 80
          sticky:
            cookie:
              name: localai_sticky
              secure: true
              httpOnly: true
  tls:
    secretName: ig-ingtra-net-tls
