apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: naraninyeo
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`naraninyeo.ig.ingtra.net`)
      services:
        - kind: Service
          name: naraninyeo
          namespace: consistent
          port: 80
  tls:
    secretName: ig-ingtra-net-tls
