apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: naraninyeo-handler
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`naraninyeo-handler.ig.ingtra.net`)
      services:
        - name: naraninyeo-main
          namespace: naraninyeo
          port: 80
          weight: 1
        - name: naraninyeo-develop
          namespace: naraninyeo
          port: 80
          weight: 5
  tls:
    secretName: ig-ingtra-net-tls
