apiVersion: v1
kind: Service
metadata:
  name: naraninyeo-main-external
spec:
  type: ExternalName
  externalName: naraninyeo-main.ks.ingtra.net
---
apiVersion: v1
kind: Service
metadata:
  name: naraninyeo-develop-external
spec:
  type: ExternalName
  externalName: naraninyeo-develop.ks.ingtra.net
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: naraninyeo-handler
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`naraninyeo-handler.ig.ingtra.net`)
      services:
        - name: naraninyeo-main-external
          port: 443
          scheme: https
          weight: 5
        - name: naraninyeo-develop-external
          port: 443
          scheme: https
          weight: 1
  tls:
    secretName: ig-ingtra-net-tls
