apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: naraninyeo-handler
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`naraninyeo-handler.ig.ingtra.net`)
      services:
        - name: naraninyeo-external
          kind: TraefikService
  tls:
    secretName: ig-ingtra-net-tls
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: naraninyeo-external
spec:
  weighted:
    services:
      - name: naraninyeo-main
        weight: 5
      - name: naraninyeo-develop
        weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: naraninyeo-main
spec:
  loadBalancer:
    servers:
      - url: "https://naraninyeo-main.ks.ingtra.net"
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: naraninyeo-develop
spec:
  loadBalancer:
    servers:
      - url: "https://naraninyeo-develop.ks.ingtra.net"
