apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        nvidia.com/gpu.product: Orin
      runtimeClassName: nvidia
      containers:
        - name: ollama
          image: ollama/ollama:0.3.7
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_REQUIRE_CUDA
              value: "cuda>=11.0"
            - name: LD_LIBRARY_PATH
              value: /usr/local/cuda/lib64
            - name: OLLAMA_MODELS
              value: /ollama
          volumeMounts:
            - name: cuda-lib
              mountPath: /usr/local/cuda/lib64
              readOnly: true
            - name: ollama
              mountPath: /ollama
          ports:
            - name: http
              containerPort: 11434
          resources:
            limits:
              cpu: "2"
              memory: "8Gi"
      volumes:
        - name: cuda-lib
          hostPath:
            path: /usr/local/cuda/lib64
            type: Directory
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
