apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: ollama
