apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "synology.dv.ingtra.net#volume1#k8s"
    volumeAttributes:
      server: synology.dv.ingtra.net
      share: /volume1/k8s
  storageClassName: synology-nfs-csi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: ollama

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
