apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: "synology.dv.ingtra.net#volume1/k8s#na/nfs-csi/ollama#"
    volumeAttributes:
      server: synology.dv.ingtra.net
      share: /volume1/k8s
      subDir: na/nfs-csi/ollama
  storageClassName: synology-nfs-csi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: ollama
