apiVersion: v1
kind: Service
metadata:
  name: qwen3-reranker-06b-jetson
  labels:
    app: qwen3-reranker-06b-jetson
spec:
  selector:
    app: qwen3-reranker-06b-jetson
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
