apiVersion: mlops.seldon.io/v1alpha1
kind: SeldonRuntime
metadata:
  name: seldon
spec:
  seldonConfig: default
  overrides:
    - name: seldon-envoy
      replicas: 2
    - name: seldon-scheduler
      disable: true
