apiVersion: v1
kind: Service
metadata:
  name: lance-3b
  labels:
    app: lance-3b
spec:
  type: ClusterIP
  selector:
    app: lance-3b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
