apiVersion: v1
kind: Service
metadata:
  name: embeddinggemma-llamacpp-cpu
  labels:
    app: embeddinggemma-llamacpp-cpu
spec:
  selector:
    app: embeddinggemma-llamacpp-cpu
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
