---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-to-elasticsearch
data:
  config.yaml: |
    logger:
      level: TRACE
      format: json
      add_timestamp: true
    input:
      kafka:
        addresses: ["kafka.mdc.ingtra.net:9092"]
        topics:
          - data.twitter.sampled-stream.1
        consumer_group: benthos-kafka-to-elasticsearch
        batching:
          count: 128
          period: 10s
    pipeline:
      processors:
        - bloblang: |
            root = this
            root."@timestamp" = meta("kafka_timestamp_unix").int64().format_timestamp_strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    output:
      elasticsearch:
        urls: ["http://opensearch.mdc.ingtra.net:9200"]
        index: ${! meta("kafka_topic") }-${! meta("kafka_timestamp_unix").int64().format_timestamp_strftime("%Y-%m-%d") }
        id: ${! meta("kafka_topic") }-${! meta("kafka_partition") }-${! meta("kafka_offset") }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-to-elasticsearch
  labels:
    app: benthos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benthos
  template:
    metadata:
      labels:
        app: benthos
    spec:
      containers:
        - name: benthos
          image: jeffail/benthos:4.13.0-cgo
          args: ["-c", "/etc/benthos/config.yaml", "-w"]
          volumeMounts:
          - name: config
            mountPath: /etc/benthos
      volumes:
        - name: config
          configMap:
            name: kafka-to-elasticsearch