apiVersion: ingtra.net/v1alpha1
kind: BenthosPipeline
metadata:
  name: kafka-to-elasticsearch
spec:
  image: harbor.ingtra.net/dockerhub/jeffail/benthos:3.64-cgo
  replicas: 1
  inlineConfig:
    logger:
      level: ALL
      format: json
      add_timestamp: true
    input:
      kafka:
        addresses: ["redpanda.mdc.ingtra.net:9092"]
        target_version: 2.8.1
        topics:
          - data.twitter.referenced-media.1
          - data.twitter.referenced-places.1
          - data.twitter.referenced-polls.1
          - data.twitter.referenced-tweets.1
          - data.twitter.referenced-users.1
          - data.twitter.sampled-tweets.1
        consumer_group: benthos-kafka-to-elasticsearch
        batching:
          count: 128
          period: 1s
    pipeline:
      processors:
        - bloblang: |
            root = this
            root."@timestamp" = (timestamp_unix_nano() / 1000000000).format_timestamp_strftime("%Y-%m-%dT%H:%M:%S.%fZ")
    output:
      elasticsearch:
        urls: ["http://elasticsearch.mdc.ingtra.net:9200"]
        index: ${! meta("kafka_topic") }-${! timestamp_unix().format_timestamp_strftime("%Y-%m-%d") }
        id: ${! meta("kafka_topic") }-${! meta("kafka_partition") }-${! meta("kafka_offset") }
        type: _doc
