apiVersion: ingtra.net/v1alpha1
kind: BenthosPipeline
metadata:
  name: kafka-to-cassandra
spec:
  image: harbor.ingtra.net/dockerhub/jeffail/benthos:3.64-cgo
  replicas: 1
  inlineConfig:
    logger:
      level: ALL
      format: json
      add_timestamp: true
    input:
      kafka:
        addresses: ["redpanda.mdc.ingtra.net:9092"]
        target_version: 2.8.1
        topics:
          - data.twitter.sampled-tweets.1
        consumer_group: benthos-kafka-to-cassandra
        batching:
          count: 128
          period: 10s
    pipeline:
      processors:
        - bloblang: |
            meta table = match meta("kafka_topic") {
              "data.twitter.sampled-tweets.1" => "twitter.sampled_tweets"
            }
    output:
      cassandra:
        addresses:
          - scylla-1.mdc.ingtra.net:9042
          - scylla-2.mdc.ingtra.net:9042
        query: INSERT INTO ? JSON ?
        args_mapping: root = [ meta("table"), this ]
