apiVersion: ingtra.net/v1alpha1
kind: BenthosPipeline
metadata:
  name: twitter-referenced-tweets-to-yugabyte
spec:
  image: harbor.ingtra.net/dockerhub/jeffail/benthos:3.64-cgo
  replicas: 1
  configInline:
    logger:
      level: DEBUG
      format: json
      add_timestamp: true
    input:
      kafka:
        addresses: ["redpanda.mdc.ingtra.net:9092"]
        target_version: 2.8.1
        topics:
          - data.twitter.referenced-tweets.1
        consumer_group: benthos-twitter-referenced-tweets-to-yugabyte
        batching:
          count: 128
          period: 10s
    output:
      sql:
        driver: postgres
        data_source_name: postgres://yugabyte:yugabyte@yugabyte-1.mdc.ingtra.net:5433/yugabyte?sslmode=disable
        query: |
          INSERT INTO twitter.referenced_tweets
          SELECT *
          FROM json_populate_record(null::twitter.referenced_tweets, $1::json)
          ON CONFLICT DO NOTHING
        args_mapping: root = [ this.string() ]
