apiVersion: ingtra.net/v1alpha1
kind: BenthosPipeline
metadata:
  name: twitter-split-stream
spec:
  image: harbor.ingtra.net/dockerhub/jeffail/benthos:3.64-cgo
  replicas: 1
  configInline:
    logger:
      level: ALL
      format: json
      add_timestamp: true
    input:
      kafka:
        addresses: ["redpanda.mdc.ingtra.net:9092"]
        target_version: 2.8.1
        topics: ["data.twitter.sampled-stream.1"]
        consumer_group: benthos-twitter-split-stream-2
        batching:
          count: 128
          period: 1s
    pipeline:
      processors:
        - bloblang: |
            let data = this.includes.key_values().map_each(item -> {"type": "referenced_" + item.key, "data": item.value}).catch([])
            let data = $data.map_each(item -> item.explode("data")).flatten()
            let data = $data.map_each(item -> item.merge({"data": {"referenced_by": this.data.id}}))
            root = $data.append({"type": "tweets", "data": this.data})
        - unarchive:
            format: json_array
        - bloblang: |
            meta output_topic = match this.type {
              "tweets" => "data.twitter.sampled-tweets.1"
              "referenced_tweets" => "data.twitter.referenced-tweets.1"
              "referenced_users" => "data.twitter.referenced-users.1"
              "referenced_places" => "data.twitter.referenced-places.1"
              "referenced_media" => "data.twitter.referenced-media.1"
              "referenced_polls" => "data.twitter.referenced-polls.1"
            }
            root = this.data
    output:
      kafka:
        addresses: ["redpanda.mdc.ingtra.net:9092"]
        target_version: 2.8.1
        topic: ${! meta("output_topic") }
        compression: zstd



