apiVersion: ingtra.net/v1alpha1
kind: BenthosPipeline
metadata:
  name: twitter-referenced-media-to-yugabyte
spec:
  image: harbor.ingtra.net/dockerhub/jeffail/benthos:3.64-cgo
  replicas: 1
  configInline:
    logger:
      level: ALL
      format: json
      add_timestamp: true
    input:
      kafka:
        addresses: ["redpanda.mdc.ingtra.net:9092"]
        target_version: 2.8.1
        topics:
          - data.twitter.referenced-media.1
        consumer_group: benthos-twitter-referenced-media-to-yugabyte
        batching:
          count: 128
          period: 10s
    pipeline:
      processors:
        - split:
            size: 1
    output:
      fallback:
        - sql:
          driver: postgres
            data_source_name: postgres://yugabyte:yugabyte@yugabyte-1.mdc.ingtra.net:5433/yugabyte?sslmode=disable
            query: |
              INSERT INTO twitter.referenced_media
              VALUES (json_populate_record(null::twitter.referenced_media, $1::json))
              ON CONFLICT DO NOTHING
            args_mapping: root = [ this.string() ]
            batching:
              count: 10
              period: 10s
        - stdout:
            codec: lines
