apiVersion: ingtra.net/v1alpha1
kind: BenthosPipeline
metadata:
  name: twitter-sampled-stream-to-yugabyte
spec:
  image: harbor.ingtra.net/dockerhub/jeffail/benthos:3.64-cgo
  replicas: 1
  configInline:
    logger:
      level: DEBUG
      format: json
      add_timestamp: true
    input:
      kafka:
        addresses: ["redpanda.mdc.ingtra.net:9092"]
        target_version: 2.8.1
        topics:
          - data.twitter.sampled-stream.1
        consumer_group: benthos-twitter-sampled-stream-to-yugabyte-5
        checkpoint_limit: 5
        batching:
          count: 1000
          period: 10s
    pipeline:
      processors:
        - bloblang: |
            root = if this.exists("data.id") {
              this
            } else {
              deleted()
            }
        - split:
            size: 100
    output:
      broker:
        pattern: greedy
        outputs:
          - sql:
              driver: postgres
              data_source_name: postgres://crate:crate@yugabyte-1.mdc.ingtra.net:5432/?sslmode=disable&connect_timeout=10
              query: |
                INSERT INTO twitter.sampled_stream
                VALUES ($1, $2::object)
                ON CONFLICT DO NOTHING
              args_mapping: root = [ this.data.id, this.string() ]
              max_in_flight: 1
