apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
spec:
  ipAddressPools:
    - default
  nodeSelectors:
    - matchLabels:
        kubernetes.io/hostname: k8s-na-work-1
    - matchLabels:
        kubernetes.io/hostname: k8s-na-work-2
  interfaces:
    - vlan396
