apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        nvidia.com/gpu.product: Orin
      runtimeClassName: nvidia
      containers:
        - name: ollama
          image: ollama/ollama:0.10.0-rc1
          args:
            - serve
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: OLLAMA_MODELS
              value: /ollama
            - name: JETSON_JETPACK
              value: "6"
          volumeMounts:
            - name: ollama
              mountPath: /ollama
          ports:
            - name: http
              containerPort: 11434
      volumes:
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama-models-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-pvc
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
