apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ollama
  namespace: ollama
  labels:
    app: ollama
spec:
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        nvidia.com/gpu.product: Orin
      runtimeClassName: nvidia
      containers:
        - name: ollama
          image: cookieshake/ollama-jetson:0.9.3
          args:
            - ollama
            - serve
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: OLLAMA_MODELS
              value: /ollama
            - name: JETSON_JETPACK
              value: "6"
          volumeMounts:
            - name: ollama
              mountPath: /ollama
          ports:
            - name: http
              containerPort: 11434
      volumes:
        - name: ollama
          hostPath:
            path: /mnt/mfs/k8s/ollama/models
            type: DirectoryOrCreate
