apiVersion: v1
kind: Service
metadata:
  name: embedding-lb
  namespace: llm-serving
spec:
  type: ExternalName
  externalName: traefik.traefik.svc.kl.ingtra.net
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: embedding-lb
  namespace: llm-serving
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`embedding-lb`)
      priority: 100
      services:
        - kind: Service
          name: embeddinggemma-300m
          namespace: llm-serving
          port: 8000
