apiVersion: v1
kind: Service
metadata:
  name: qwen3-vl-embedding-2b
  labels:
    app: qwen3-vl-embedding-2b
spec:
  selector:
    app: qwen3-vl-embedding-2b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
