apiVersion: v1
kind: Service
metadata:
  name: embeddinggemma-300m
  labels:
    app: embeddinggemma-300m
spec:
  selector:
    app: embeddinggemma-300m
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
