apiVersion: v1
kind: Service
metadata:
  name: qwen3-embedding-0-6b
  labels:
    app: qwen3-embedding-0-6b
spec:
  selector:
    app: qwen3-embedding-0-6b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
