apiVersion: v1
kind: Service
metadata:
  name: triton
  labels:
    app: triton
spec:
  selector:
    app: triton
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: grpc
      port: 8001
      targetPort: 8001
      protocol: TCP
    - name: metrics
      port: 8002
      targetPort: 8002
      protocol: TCP
  type: ClusterIP
