apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-4b-2507
  namespace: llm-serving
  labels:
    app: qwen3-4b-2507
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-4b-2507
  template:
    metadata:
      labels:
        app: qwen3-4b-2507
    spec:
      runtimeClassName: nvidia
      containers:
        - name: llama-cpp
          image: docker.io/cookieshake/llamacpp-jetson:b6092
          imagePullPolicy: Always
          args:
            - --host
            - "0.0.0.0"
            - --port
            - "8080"
            - --parallel
            - "3"
            - --n-gpu-layers
            - "999"
            - --hf-repo
            - unsloth/Qwen3-4B-Instruct-2507-GGUF:UD-Q3_K_XL
            - --jinja
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LLAMA_CACHE
              value: /opt/llama_cpp/cache
          volumeMounts:
            - name: cache-volume
              mountPath: /opt/llama_cpp/cache
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 100
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: cache-volume
          hostPath:
            path: /mnt/mfs/k8s/llama_cpp/cache
            type: DirectoryOrCreate
      nodeSelector:
        nvidia.com/gpu.product: Orin
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-4b-2507
  namespace: llm-serving
  labels:
    app: qwen3-4b-2507
spec:
  selector:
    app: qwen3-4b-2507
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
