apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-words-are-bad
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bad-words-are-bad
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bad-words-are-bad
    spec:
      containers:
        - name: bad-words-are-bad
          image: harbor.ingtra.net/library/mosec-models:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: "4"
              memory: 4Gi
      nodeSelector:
        kubernetes.io/arch: amd64

---
apiVersion: v1
kind: Service
metadata:
  name: bad-words-are-bad
spec:
  selector:
    app.kubernetes.io/name: bad-words-are-bad
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
