apiVersion: apps/v1
kind: Deployment
metadata:
  name: omniamni
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: omniamni
  template:
    metadata:
      labels:
        app.kubernetes.io/name: omniamni
    spec:
      containers:
        - name: omniamni
          image: harbor.ingtra.net/library/omniamni:latest
          imagePullPolicy: Always
          env:
            - name: OLLAMA_SERVER_URL
              value: http://ollama.ollama.svc.cluster.local
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: "1"
              memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: omniamni
spec:
  selector:
    app.kubernetes.io/name: omniamni
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
