apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: amoro
  namespace: amoro
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "k8s/amoro/amoro-database"