---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: code-server
  namespace: code-server
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "k8s/code-server/code-server"
