apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
  namespace: coder
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "k8s/coder/secrets"
