apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubero-secrets
  namespace: kubero
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: "k8s/kubero/secrets"
