---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  namespace: example
spec:
  provider:
    vault:
      server: "http://vault.vd.ingtra.net:8200"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          namespace: "external-secrets"
          name: "vault-token"
          key: "token"
