apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl
spec:
  acme:
    email: cookieshake.dev@gmail.com
    server: https://acme.zerossl.com/v2/DV90
    privateKeySecretRef:
      name: zerossl-private-key
    solvers:
    - dns01:
        cloudflare:
          email: cookieshake.dev@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token