apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.ig.ingtra.net`)
      services:
        - kind: Service
          name: argocd-server
          namespace: argocd
          port: 80
