apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: code-server
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`code-server.ig.ingtra.net`)
      services:
        - kind: Service
          name: code-server
          namespace: code-server
          port: 8080
  tls:
    secretName: ig-ingtra-net-tls
