apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupang-partners-proxy
spec:
  selector:
    matchLabels:
      app: coupang-partners-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: coupang-partners-proxy
    spec:
      containers:
        - name: coupang-partners-proxy
          image: harbor.ingtra.net/library/coupang-partners-proxy
          imagePullPolicy: Always
          env:
            - name: PARTNERS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: partners-api-keys
                  key: access-key
            - name: PARTNERS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: partners-api-keys
                  key: secret-key
            - name: REDIS_URI
              value: redis://redis.mdc.ingtra.net:6379/1
          ports:
            - containerPort: 8000