apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      nodeSelector:
        nvidia.com/gpu.product: Orin
      runtimeClassName: nvidia
      containers:
        - name: ollama
          image: ollama/ollama:0.1.20
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_REQUIRE_CUDA
              value: "cuda>=11.0"
            - name: LD_LIBRARY_PATH
              value: /usr/local/cuda/lib64
          volumeMounts:
            - name: cuda-lib
              mountPath: /usr/local/cuda/lib64
              readOnly: true
          ports:
            - containerPort: 11434
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
        - name: ollama-init
          image: ollama/ollama:0.1.20
          command: ["/bin/bash"]
          args:
            - -c
            - |
              set -ex
              sleep 10
              ollama pull phi
              sleep infinity
          resources:
            limits:
              cpu: 100m
              memory: "128Mi"
      volumes:
        - name: cuda-lib
          hostPath:
            path: /usr/local/cuda/lib64
            type: Directory