---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: kyuubi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: kyuubi
subjects:
  - kind: ServiceAccount
    name: spark
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io