apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clearml-app
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`app.clearml.ig.ingtra.net`)
      services:
        - kind: Service
          name: clearml-webserver
          namespace: clearml
          port: 8080
  tls:
    secretName: clearml-ig-ingtra-net-tls

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clearml-api
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.clearml.ig.ingtra.net`)
      services:
        - kind: Service
          name: clearml-apiserver
          namespace: clearml
          port: 8008
  tls:
    secretName: clearml-ig-ingtra-net-tls

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clearml-files
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`files.clearml.ig.ingtra.net`)
      services:
        - kind: Service
          name: clearml-fileserver
          namespace: clearml
          port: 8081
  tls:
    secretName: clearml-ig-ingtra-net-tls
