apiVersion: v1
kind: PersistentVolume
metadata:
  name: trino-exchange
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: synology-nfs-csi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trino-exchange
  namespace: trino
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: trino-exchange
