apiVersion: v1
kind: Service
metadata:
  name: filestash
spec:
  type: ClusterIP
  selector:
    app: filestash
  ports:
  - protocol: TCP
    port: 8334
    targetPort: 8334

---
apiVersion: v1
kind: Service
metadata:
  name: filestash-wopi
spec:
  selector:
    app: filestash-wopi
  ports:
  - protocol: TCP
    port: 9980
    targetPort: 9980